### ISSUE TITLE
Crash on Opening

### ISSUE THREAD

**Issue by drtoboggan2814** [Decimation/SmartImage#18]
When I try to open SmartImage, this error is generated:

Unhandled exception. System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.DllNotFoundException: Dll was not found.
   at WinRT.Platform.WindowsCreateStringReference(Char* sourceString, Int32 length, IntPtr* hstring_header, IntPtr* hstring)
   at WinRT.MarshalString.CreateMarshaler(String value)
   at WinRT.WinrtModule.GetActivationFactory(String runtimeClassId)
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
   at Windows.System.UserProfile.GlobalizationPreferences._IGlobalizationPreferencesStatics..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance[T]()
   at WinRT.WeakLazy`1.get_Value()
   at Windows.System.UserProfile.GlobalizationPreferences._IGlobalizationPreferencesStatics.get_Instance()
   at Windows.System.UserProfile.GlobalizationPreferences.get_Languages()
   at SmartImage.Core.AppInfo.Setup()
   at .cctor()
   --- End of inner exception stack trace ---

I have .NET 5.0.11, and am on Windows 7 64 bit.

**Comment by Decimation** [comment]
Can you try the latest release, v2.1.9?
